### PR TITLE
get value from local storage or use initial value

### PR DESCRIPTION
**Pull request by lilasquared**
you were returning initial value even when one was set in local storage

### CODE REVIEW

**Comment by dance2die** [comment]
# 🤔 😅 😲

Thanks @lilasquared~~~ 
You are right. If the value already existed, then that value should be returned 🙏

**Comment by dance2die** [comment]
@all-contributors please add @lilasquared for bug, code

**Comment by dance2die** [comment]
I've released `v2.3.0` as it was such a bad 🐛 on my part 😅

Thank you again, and I will add tests in later stage as I did with [dance2die/calendar-dates](https://github.com/dance2die/calendar-dates)

**Comment by lilasquared** [comment]
Thanks!  I am using it in a playground to play with hooks so it was easy to fix 👍

**Pull request merged**
